export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_DEFAULT_ITEM_REQUEST = 'POST_DEFAULT_ITEM_REQUEST';
export const POST_DEFAULT_ITEM_SUCCESS = 'POST_DEFAULT_ITEM_SUCCESS';
export const POST_DEFAULT_ITEM_FAIL = 'POST_DEFAULT_ITEM_FAIL';
